backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
display_url: http://localhost:8000
media_folder: 'site/static/assets/'
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    files:
        - label: "Home Page"
          name: "home"
          file: 'site/src/pages/pageData/home.md'
          fields:
              - {label: "Page Title", name: "title", widget: "string"}
              - label: "Jumbotron"
                name: 'jumbotron'
                widget: 'object'
                fields:
                - {label: "Jumbo Header", name: "jumboHeader", widget: "string"}
                - {label: "Jumbo Subheader", name: "jumboSubheader", widget: "string"}
                - {label: "Video URL", name: "videoUrl", widget: "string"}
                - {label: "Video CTA", name: "videoCta", widget: "string"}
                - {label: "Icon", name: 'videoCTAIcon', widget: 'image'}
              - label: Services
                name: services
                widget: 'object'
                fields:
                  - {label: "Title", name: 'title', widget: 'string'}
                  - {label: "Icon", name: 'icon', widget: 'image'}
                  - label: Cards
                    name: cards
                    widget: 'list'
                    fields:
                      - {label: "Card Title", name: "cardTitle", widget: 'string'}
                      - {label: "Card Subtitle", name: "cardSubtitle", widget: 'string'}
                      - {label: "Icon", name: "icon", widget: 'image'}
              - label: Values
                name: values
                widget: 'object'
                fields:
                  - {label: "Title", name: "valueTitle", widget: 'string'}
                  - {label: "Icon", name: "icon", widget: 'image'}
                  -  label: Values List
                     name: valuesList
                     widget: 'list'
                     fields:
                         - {label: "Value", name: "value", widget: 'string'}
              - label: Offers
                name: offers
                widget: 'object'
                fields:
                  - {label: "Title", name: 'title', widget: 'string'}
                  - {label: "Icon", name: 'icon', widget: 'image'}
                  - label: Cards
                    name: cards
                    widget: 'list'
                    fields:
                      - {label: "Card Title", name: "cardTitle", widget: 'string'}
                      - {label: "Card Subtitle", name: "cardSubtitle", widget: 'string'}
                      - {label: "Icon", name: "icon", widget: 'image'}
              - label: "Footer"
                name: 'footer'
                widget: 'object'
                fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
                - {label: "Contact", name: 'contact', widget: "string"}
        - name: "nav-links" # Used in routes, e.g., /admin/collections/blog
          label: 'Nav Links'
          file: "site/src/pages/pageData/navData.md"
          fields:
            - {label: "Title", name: 'title', widget: 'string'}
            - label: Nav Items
              name: navItems
              widget: "list"
              fields:
                - {label: Name, name: name, widget: string}
                - {label: URL, name: url, widget: string}
